version: '3'
services:
  db:
    image: postgres
    volumes:
      - $HOME/srv/postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "0.0.0.0:5432:5432"
    restart: always
  casino-backend:
    image: eclipse-temurin:latest
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - "db"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
